name = "sharehog"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
POSTHOG_API_KEY = "phc_BpQAfUqbcCH2T7fDUU7PaiSGeoFAAbTYcwFeRh8oQF6q"
POSTHOG_HOST = "https://eu.i.posthog.com"

[[d1_databases]]
binding = "DB"
database_name = "sharehog-db"
database_id = "d39f7592-2697-459b-868c-70548e568ad8"
